<template>
  <v-dialog
    v-model="showModal"
    :persistent="persistent"
    origin="center center"
    width="460"
    class="authDialog"
  >
    <v-card class="authCard">
      <div class="modal_content fPassword">
        <form class="content_area">
          <v-row class="row_form">
            <div class="col-12 logo">
              <img src="/images/png/logo.png" alt="" />
            </div>
            <div class="col-12" style="padding-bottom: 0; padding-top: 0">
              <header>Forgot Password</header>
            </div>
            <div class="col-12 fPassword_text">
              <p>
                Please enter your email adress and we will send a code to reset
                your password.
              </p>
            </div>
            <div class="col-12" :class="{ activeInput: login.email }">
              <label for="loginEmail">Email address</label>
              <input
                required
                id="loginEmail"
                type="email"
                name=""
                v-model="login.email"
              />
            </div>
            <div class="col-12 submit_wrapper">
              <v-btn
                @click="getToken"
                :disabled="!login.email || loading"
                class="Btn"
              >
                <span v-if="!loading">Submit</span>
                <svg
                  v-else
                  xmlns="http://www.w3.org/2000/svg"
                  xmlns:xlink="http://www.w3.org/1999/xlink"
                  style="
                    margin: auto;
                    background: none;
                    display: block;
                    shape-rendering: auto;
                  "
                  width="75"
                  height="75"
                  viewBox="0 0 100 100"
                  preserveAspectRatio="xMidYMid"
                >
                  <circle
                    cx="50"
                    cy="50"
                    fill="none"
                    stroke="var(--primary-color)"
                    stroke-width="4"
                    r="22"
                    stroke-dasharray="103.67255756846316 36.55751918948772"
                  >
                    <animateTransform
                      attributeName="transform"
                      type="rotate"
                      repeatCount="indefinite"
                      dur="1s"
                      values="0 50 50;360 50 50"
                      keyTimes="0;1"
                    ></animateTransform>
                  </circle>
                  <!-- [ldio] generated by https://loading.io/ -->
                </svg>
              </v-btn>
            </div>
          </v-row>
        </form>
      </div>
    </v-card>
  </v-dialog>
</template>

<script>
export default {
  emit: ["showToken"],
  data() {
    return {
      showModal: true,
      fullScreenModal: false,
      persistent: true,
      loading: false,
      login: {
        email: "",
      },
      errors: {},
    };
  },
  mounted() {
    var nx = window.innerWidth;
    if (nx <= 959) {
      this.fullScreenModal = true;
    }
    window.addEventListener("resize", function (event) {
      var w = window.innerWidth;
      nx = w;
    });
    $(window).resize(() => {
      if (nx <= 959) {
        this.fullScreenModal = true;
      } else {
        this.fullScreenModal = false;
      }
    });
  },
  methods: {
    getToken() {
      this.$emit("showToken");
      this.showModal = false;
      this.login = {
        email: "",
      };
    },
  },
};
</script>

<style scoped>
</style>